### ISSUE TITLE
Eclipse Quick Text Search can't find text after line longer than 1000 chars

### ISSUE THREAD

**Issue by petrf22** [spring-projects/eclipse-integration-commons#27]
Hi.
I have properties file with long lines.
If is line longer than 1000 chars, Quick Text Search can't find text behind this longer line.

For example my properties file:
```
a=a_text_a
b=345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901
c=c_text_c
```

Quick text search found's "a_text_a", but didn't found "c_text_c".

Eclipse Quicksearch	3.9.10.201906242213-CI-B472	org.springsource.ide.eclipse.commons.quicksearch.feature.feature.group	Pivotal Software, Inc.
Eclipse Version: 2019-06 (4.12.0), Build id: 20190614-1200
Windows 10/64, Java 8/64

Thank you for your work
Petr

**Comment by martinlippert** [comment]
@kdvolder can you have a look and in case you can reproduce this, fix it on the Eclipse side?

**Comment by kdvolder** [comment]
This is actually by design rather than a 'bug'. The long lines are taken as a signal that the file is probably something like minified .js rather than a 'real' source file that you actually want to search. I added this heuristic a long time ago because it bothered me a great deal to see matches in files like that.

So... can I reproduce this... Yes! 

Can we fix this? We could remove the heuristic or make it optional, or make the number of the cut-of configurable somehow. Removing it would probably have the annoying side effect that matches in these kinds of minified files would start showing up which is not desirable.

Best is probably to make this configurable.

**Comment by petrf22** [comment]
Hi.
Thank you for explaining the problem. I understand it.
My problem was caused by using JBoss Tools Properties Editor, which writes
long text with char "LF" or "CRLF" as a single line with a delimiter "\n".
It is an excellent helper for storing SQL queries in internal properties
files.
If you had the time and desire to deal with the problem, I would be very
grateful to you.
Setting up using file types is a great idea and was a good solution for me.
Thank you very much for your time.
Petr Franta

čt 1. 8. 2019 v 16:31 odesílatel Kris De Volder <notifications@github.com>
napsal:

**Comment by kdvolder** [comment]
I think it is worth doing something to address this issue. But it needs a bit of thought exactly what should be done. I don't think just disabling the heuristic is the answer. 

Should also mention that since we are in the process of contributing the quicksearch to Eclipse, this issue should probably be raised as bug report with Eclipse bugzilla to fix it in the future. 

There's little point in trying to fix the STS version at this point.

**Comment by kdvolder** [comment]
Actually, I just realized that this issue is in fact already addressed a really long time ago:

https://jira.spring.io/browse/STS-4033

There's a preference in the Quicksearch preference page to change the lenght at which this heuristic is triggered. So all that you really have to do is make it larger.

**Comment by petrf22** [comment]
Thank you for your time and information.
